### PR TITLE
fix: can no longer authenticate manually while automatic authentication is in progress

### LINKED ISSUE #179: If automatic authentication is slow, the user has the ability to press the login button, causing both manual and automatic authentication. This results in unexpected behaviour.
# Issue 
If the user initiates manual authentication while automatic authentication is running, the following will happen (in Expense & Pay, and probably other apps):
- While the user tries authenticating manually, the app navigates to releasenotes screen
- The releasenotes screen, which has no releasenotes to display, navigates the user to the root screen
- When the user finishes the manual authentication, the app navigates the user back to releasenotes screen. The releasenotes screen is now completely blank, and has no option to navigate anywhere else

# Solution
- Disable the "Log in" button while the app tries automatic authentication

### PR DESCRIPTION
**Pull request by tormodAase**
Users with slow connection/hardware might click the login button while automatic authentication is in progress, resulting the user getting stuck on a blank releasenotes screen. This PR removes the ability to press "Log in" while automatic authentication is in progress.

Closes #179

### CODE REVIEW

**Review by PtjeEquinor — APPROVED** [review]

File: src/screens/LoginScreen.tsx [hunk 1]
```diff
@@ -50,6 +52,7 @@ export default function LoginScreen(props: {
             track(metricKeys.AUTHENTICATION_AUTOMATIC);
             props.navigation.navigate(props.mainRoute);
           }
+          setSilentAuthenticationFinished(true);
```
Comment (HaakonSvane) [inline src/screens/LoginScreen.tsx:55]: With this solution, what happens when login fails, but a user presses the button again? It does not seem like the spinner would ever appear again after first login attempt.

**Review by HaakonSvane — APPROVED** [review]
Good stuff good stuff. I left a question about the inAuth progress detection method.

File: src/screens/LoginScreen.tsx (hunk 1 above)
Comment (tormodAase) [reply src/screens/LoginScreen.tsx:55]: Silent authentication only happens once, so the spinner should never re-appear unless the app is restarted. When you press sign out in the settings screen, you navigate back to the login screen, which should not trigger a new mount. Even if it did trigger a new mount in some apps, it wouldn't matter cuz the silent authentication would fail after sign-out, so you wouldn't run into the issue we are fixing here

Comment (HaakonSvane) [reply src/screens/LoginScreen.tsx:55]: Gotcha 🥇

Comment (tormodAase) [reply src/screens/LoginScreen.tsx:55]: To make it more robust, I could add a `setSilentAuthenticationFinished(false)` before authenticating silently
